### ISSUE TITLE
I created a new version that is nodejs based and uses the official PCSO results page

### ISSUE THREAD

**Issue by mxaddict** [jefjabs/lotto-scraper-ph#1]
I created a new version that is nodejs based and uses the official PCSO results page

Please add to the README in the versions SECTION :+1: 

https://github.com/mxaddict/lotto-scraper-ph-nodejs

**Comment by jefjabs** [comment]
Ooooh Ryts.. Hahaha.

**Comment by mxaddict** [comment]
Imu nang gi add sa imung README.md? Hahaha

BTW, ako ning gi compose na email sa VIM, check out the attached file.

Trolololol

**Comment by jefjabs** [comment]
Imbaha oi!. haha.. VIM fanboyism syndrome na mn na bar.. hahahahaha.
Oo, nabutang na nako sa README nako bar.
Murag kaning imong node version ra jd ang functional rn bar, wala pa nako maupdate ako mga URLs, patay na tanan.. hahaha

**Comment by mxaddict** [comment]
Hahaha

Cheers,
Barry Deeney

**Comment by mxaddict** [comment]
Ikaw? Dili ka mo balik sa VIM? :) Hahaha

**Comment by jefjabs** [comment]
hahahaha.. wala mn gd ko nibulag sa VIM.. VIM gihapon ko rn........ sa MacOS lang.. hahahahaha..

**Comment by mxaddict** [comment]
Aw, hahaha

Ei check nya ning akong new MUTT configs sa akong dotfiles sa gitlab,
kay naa diri akong configs para mo work sa GMAIL akong terminal based
email client, lingaw kaayu ko gamit ani kay mag compose kog emails VIA
VIM na, nya paspas kaayu ko maka reply sa emails kay all keyboard
shortcuts, hhahaha :P

#getrekt na ang webmail, never gonna go back, bwahahaha

**Comment by jefjabs** [comment]
hahaha.. geh2.. check ra nya nako.. VIM ftw! haha..
